"""add uuid api key

Revision ID: 8f4342e597a4
Revises: 1079d20df42b
Create Date: 2025-03-12 13:08:50.827828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4342e597a4'
down_revision: Union[str, None] = '1079d20df42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uuid_api_key')
    # ### end Alembic commands ###
